apps:
  smlab:
    command: 'bin/smlab'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/smlab/issues'
description: 'Generate StepMania dance-single charts from audio using machine learning.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/smlab/issues'
license: 'MIT'
name: 'smlab'
parts:
  smlab:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/smlab'
summary: 'Generate StepMania dance-single charts from audio using machine learning.'
title: 'smlab'
version: '0.0.0'
website: 'https://tatsh.github.io/smlab/'
